addresses the TypeError raised when 'new' is None (#4)
Sometimes this message appears on deployments:
```
Traceback (most recent call last):
  File "/home/circleci/.venv/bin/nyprsetuptools", line 7, in <module>
    run_cmd()
  File "/home/circleci/.venv/lib/python3.6/site-packages/nyprsetuptools/util/cli.py", line 55, in run_cmd
    cmd.run()
  File "/home/circleci/.venv/lib/python3.6/site-packages/nyprsetuptools/commands/deploy.py", line 396, in run
    self.update_service(cluster_name, task_name, task_definition_arn)
  File "/home/circleci/.venv/lib/python3.6/site-packages/nyprsetuptools/commands/deploy.py", line 339, in update_service
    to_start = new['desiredCount'] - new['runningCount']
TypeError: 'NoneType' object is not subscriptable
Exited with code 1
```